### ISSUE TITLE
添加失败

### ISSUE THREAD

**Issue by adui-dev** [joeyHXD/dota2_watcher_bot#5]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/51226005/202182648-79d4b22f-e770-4360-9391-fbfd1ed23d61.png">

**Comment by adui-dev** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/51226005/202183029-6e7a7a8b-a333-4d66-9d1e-04da62a9b3f0.png">

**Comment by joeyHXD** [comment]
不@bot应该就行了，你试试？

**Comment by joeyHXD** [comment]
还有就是连到steam api的url时应该是超时了，你可能要试试弄个代理，这个可以在`DOTA2.py`里面填

**Comment by adui-dev** [comment]
那就寄了，么得代理

发件人: joeyHXD ***@***.***>
日期: 星期三, 2022年11月16日 21:11
收件人: joeyHXD/dota2_watcher_bot ***@***.***>
抄送: Laird-Lee ***@***.***>, Author ***@***.***>
主题: Re: [joeyHXD/dota2_watcher_bot] 添加失败 (Issue #5)

还有就是连到steam api的url时应该是超时了，你可能要试试弄个代理，这个可以在DOTA2.py里面填

―
