### ISSUE TITLE
日志卡在getting message是什么情况，机器人也卡死了

### ISSUE THREAD

**Issue by StockingYang** [joeyHXD/dota2_watcher_bot#6]
![image](https://user-images.githubusercontent.com/38910621/225231106-bab8b123-7efc-48bb-a1c7-eb6d84b9708f.png)

**Comment by joeyHXD** [comment]
不太清楚诶，我晚上会测试一下，自从7.32我就没用过这个功能了

**Comment by joeyHXD** [comment]
读了一下代码，发现我以前写的是单线程的，所以从网页获取数据时卡住了，整个bot就不动了。。在改了，顺带重构一下代码，估计要个几天。
目前你可以先检查一下你的网络问题，steamapi有时候需要代理才能连接的。

**Comment by StockingYang** [comment]
我检查了下确实是steam api寄了，可惜腾讯云跑代理太恶心了根本没法连。。。我试试能不能用openDOTA的api去替换下steamapi吧

**Comment by joeyHXD** [comment]
行，我周末有空也看看你说的openDOTA

**Comment by joeyHXD** [comment]
更新了，现在应该就算网卡住也不会卡住整个bot了

**Comment by joeyHXD** [comment]
注意做好备份再git pull, 需要重新输入玩家账号

**Comment by StockingYang** [comment]
好的老哥
