### ISSUE TITLE
查询报错IndexError: list index out of range

### ISSUE THREAD

**Issue by beast27** [joeyHXD/dota2_watcher_bot#9]
![20230429221857](https://user-images.githubusercontent.com/11132474/235307683-d7ca1f9d-4b6b-43e9-ae91-6d9f3eee9839.png)
请问这大概是什么东西引起的问题，在dotabuff.com上能看到比赛。

**Comment by joeyHXD** [comment]
没见过的bug，应该是player_list为空了，你能发我一下你的steamid和match id吗？
你打的是匹配，排位还是人机？

**Comment by joeyHXD** [comment]
~~~
new_list = []
    for player in player_list:
        for player_game_info in match_info['players']:
            if player.short_steamID == player_game_info['account_id']:
                player.load_player_info(player_game_info)
                new_list.append(player)
                break
        else:
            print(f"{player.nickname}的数据无法获取，可能已被屏蔽")
~~~
line18-26行这里没在account_id里找到你的id，导致player_list为空了

**Comment by joeyHXD** [comment]
> 没见过的bug，应该是player_list为空了，你能发我一下你的steamid和match id吗？ 你打的是匹配，排位还是人机？

我QQ是2241192063，你可以私我吧

**Comment by beast27** [comment]
是不是因为我绑的id是17位的那个？

**Comment by joeyHXD** [comment]
> 是不是因为我绑的id是17位的那个？

哦是的，api上account_id是短的那个

**Comment by beast27** [comment]
破案了，用dotabuff里短的9位id就查出来了，我不玩dota不太清楚id，不好意思。
奇怪的是即使绑的长id，机器人在赛后秒出这个错误提示，平时没有错误信息。
